[package]
name = "keep-presence"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = "1.7.1"
chrono = "0.4.38"
enigo = "0.2.1"
env_logger = "0.11.5"
femme = "2.2.1"
floem = "0.2.0"
kv-log-macro = "1.0.7"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
